// authorization
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// notification
export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";

export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_ALL_COURSES_BY_STUDENT = "GET_ALL_COURSES_BY_STUDENT";

export const SUBSCRIBE_TO_COURSE = "SUBSCRIBE_TO_COURSE";
export const UNSUBSCRIBE_TO_COURSE = "UNSUBSCRIBE_TO_COURSE";
